<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Hinge-Setup</AssemblyName>
    <Version>1.0.32</Version>
    <AssemblyVersion>1.0.32.0</AssemblyVersion>
    <FileVersion>1.0.32.0</FileVersion>
    <InformationalVersion>1.0.32</InformationalVersion>
    <RootNamespace>Hinge.Setup</RootNamespace>
    <ApplicationIcon>..\windows\Hinge.App\Assets\app_icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>
</Project>
